[project]
name = "beets-vocadb"
version = "0.0.1"
description = "Plugin for beets to use VocaDB (or similar) as an autotagger source."
authors = [
    { name = "prTopi", email = "17724308+prTopi@users.noreply.github.com" },
]
license = { text = "MIT" }
classifiers = [
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Multimedia :: Sound/Audio :: Players :: MP3",
    "License :: OSI Approved :: MIT License",
    "Environment :: Console",
    "Environment :: Web Environment",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
]
dynamic = ["readme", "dependencies"]

[tool.basedpyright]
pythonVersion = "3.10"

[tool.setuptools.dynamic]
readme = { file = ["README.md"] }
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.packages.find]
exclude = ["typings"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
